[package]
name = "dump-assembly"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.7"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
strip = "symbols"
debug = false
panic = "abort"
opt-level = "z"
codegen-units = 1
