name: Give me files for reverse engineering
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Steal some files for me to analyze
        run: |
          Copy-Item C:\Windows\System32\kernel32.dll .\
          Copy-Item C:\actions\runner-provisioner-Windows\hostfxr.dll .\
          Copy-Item -Recurse C:\actions\runner-provisioner-Windows .\

      - uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: |
            kernel32.dll
            hostfxr.dll

      - uses: actions/upload-artifact@v3
        with:
          name: program
          path: runner-provisioner-Windows
